useTabs: true
tabWidth: 2
printWidth: 100
# xml末尾">"不单独一行
bracketSameLine: true
singleQuote: true
semi: true
quoteProps: 'as-needed'
jsxSingleQuote: false
trailingComma: 'all'
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: 'always'
rangeStart: 0
requirePragma: false
insertPragma: false
proseWrap: 'preserve'
htmlWhitespaceSensitivity: 'css'
endOfLine: 'lf'
